<?php
include_once __DIR__ . '/../includes/funciones.php';



$partidosDiputados = [
    // Atlántida (8 diputados)
    'Atlántida' => [
        'Partido Liberal' => [
            'ALFONZO ORDOÑEZ RODRIGUEZ', 'ALEJANDRO ANTONIO CANELAS CARDONA', 'JOSE DOMINGO HENRIQUEZ MACHADO',
            'ENAN ESAU OCHOA FERRUFINO', 'KERISHA ZONALY SPICER CLARK', 'GLORIA JOSSELLY ARITA PORTILLO',
            'FANNY KARINA CABRERA GUARDADO', 'ANA GABRIELA MARTINEZ GARAY'
        ],
        'Partido Nacional' => [
            'MARCO ANTONIO MIDENCE MILLA', 'DAVID SANIN MANAIZA RAMIREZ', 'REMBERTO ALEXANDER ZAVALA ROZALES',
            'MARLA YADIRA ESCOBAR MONTUFAR', 'IVETH OBDULIA MATUTE BETANCOURTH', 'MARCIO RENE ESPINAL CARDONA',
            'ADELA ESMERALDA MARTINEZ', 'MARILU AGUILAR'
        ],
        'LIBRE' => [
            'ENRIQUE ALEJANDRO MATUTE DIAZ', 'OSCAR ARIEL MONTOYA RODEZNO', 'ANAEL MENDEZ RIVERA',
            'MARIO RENE CONTRERAS HERNANDEZ', 'MARLENE ISABEL SANCHEZ SOLIS', 'JOSELYN MARITZA ARDON GARCIA',
            'ZULMY ARELY LOPEZ NUFIO', 'CARLOS ALFREDO ENAMORADO CARCAMO'
        ],
        'PSH' => [
            'TOMAS ANTONIO RAMIREZ HERNANDEZ', 'LORENA EDHIT VILLAFRANCA NUÑEZ', 'MARIO RENE ORTEGA CASTILLO',
            'ANA ISABEL JIMENEZ MAJANO', 'ALIRIO JOSE ARGUETA CRUZ', 'GRICELDA MURILLO MARTINEZ',
            'INGRIS YELENI GARCIA PEÑA', 'JORGE ROBERTO ORELLANA GARCIA'
        ],
        'DC' => [
            'KENNIA YAMILETH MONTERO MARTINEZ', 'JOSE ANTONIO GALDAMES FUENTES', 'LUIS BERNARDO SARMIENTO NUÑEZ',
            'INGRID ESTEFANIE SAMPSON RIVERA', 'ENRIQUE NASSAR BENITEZ', 'JORGE ALBERTO BUSTILLO ACOSTA',
            'NIDIA WALESKA ESCOBAR PINEDA', 'BERTHA MARIA GARCIA VELIZ'
        ]
    ],

    // Choluteca (9 diputados)
    'Choluteca' => [
        'Partido Nacional' => [
            'DILER MAURICIO MARTINEZ HERNANDEZ', 'CARLOS ROBERTO LEDEZMA CASCO', 'JAVIER ALEJANDRO MENDIETA SERVELLON',
            'ILEANA NAZARETH VELASQUEZ ORDOÑEZ', 'EDGARDO HERNAN LOUCEL AGUILERA', 'FRANCIS YOLANDA ARGEÑAL ECHENIQUE',
            'YOSELIN STEPFANIE CABRERA VASQUEZ', 'MARIA ORFILIA CHINCHILLA CHACON', 'IGNACIO ANTONIO MORENO SEVILLA'
        ],
        'Partido Liberal' => [
            'YURY CRISTHIAN SABAS GUTIERREZ', 'ALEX REMBERTO ORDOÑEZ ORDOÑEZ', 'LUIS FERNANDO COELLO',
            'MENFFIS SAMANTHA VALLADARES SANCHEZ', 'DAVID CARRANZA OCHOA', 'KAREN GISSEL TALAVERA PONCE',
            'AMILCAR REINALDO RIVAS', 'SANDRA RAQUEL ROJAS AVILA', 'LUZ ARMIDA ALVAREZ CHAVEZ'
        ],
        'LIBRE' => [
            'LUIS ENRIQUE ORTEGA SANCHEZ', 'NIDIA GISSELA CASTILLO FUNEZ', 'EDGARDO ALCIDES VARGAS PADILLA',
            'LUIS GEOVANY MARTINEZ SANCHEZ', 'GUSTAVO ALBERTO CACERES BANEGAS', 'ENRIQUE EDUARDO ARIAS GUILLEN',
            'VICTOR ALFONSO GALO MARADIAGA', 'YASMINA LIZET FUENTES FONSECA', 'MELIDA ELIZABETH HERRERA NUÑEZ'
        ],
        'DC' => [
            'JOSE LUCIANO ORTIZ RODRIGUEZ', 'CARLOS ALBERTO CARRANZA ESTRADA', 'DARIELA ALEJANDRA GUANDIQUE BOCK',
            'JAVIER MAURICIO AGUILAR MONTOYA', 'BESSY XIOMARA CONTRERAS FLORES', 'JIMY YONI MARADIAGA BAQUEDANO',
            'KELVIN FARID RODRIGUEZ MARTINEZ', 'KATHERIN DARIELA CASTILLO MENDEZ', 'DILEYLA VANESSA ESPINOZA'
        ],
        'PSH' => [
            'MERLIN MOISES CORRALES ORDOÑEZ', 'JANORY CHRISDEL RAUDALES VIERA', 'FABIOLA LOPEZ CACERES',
            'YELSON TEODORO AGUILAR FLORES', 'ALEX ENRIQUE LOPEZ SANCHEZ', 'GLORIA AZUCENA MARTINEZ GUILLEN',
            'GERSON HERNANDEZ OVIEDO', 'YENIS KARINA AGUIRRE MEJIA', 'ARIEL HUMBERTO SAUCEDA MONDRAGON'
        ]
    ],

    // Colón (4 diputados)
    'Colón' => [
        'Partido Nacional' => [
            'JUAN ALBERTO SAUCEDA CARDONA', 'ARIANA MELISSA BANEGAS CARCAMO', 'ELDA ISAURA MEJIA GARCIA', 'DANY SALVADOR SANCHEZ JACKSON'
        ],
        'LIBRE' => [
            'MARCO AURELIO MARADIAGA MOLINA', 'DAIRI JAVIER AVILA GABARRETE', 'SHERLY ADRIANA LOBO BONILLA', 'DIGNA ISABEL VELASQUEZ CARDONA'
        ],
        'Partido Liberal' => [
            'TIBDEO RICARDO ELENCOFF MARTINEZ', 'CARLOS RENE ECHEVERRIA MATUTE', 'BESSY KARINA GARCIA TURCIOS', 'BARBARA MARCELA VARELA RIVERA'
        ],
        'PSH' => [
            'LETICIA LIZETH ROMERO ROSALES', 'LISANDRO ARRIOLA SOLANO', 'MARITZA MARISOL MUNGUIA', 'ALEXANDER ARIEL DURON MARTINEZ'
        ]
    ],

    // Comayagua (7 diputados)
    'Comayagua' => [
        'Partido Nacional' => [
            'ADRIAN JOSUE MARTINEZ SOLER', 'JUAN CARLOS VARGAS RIOS', 'CARLOS ALBERTO MEZA MEJIA',
            'DANIEL HUMBERTO DISCUA GUIFARRO', 'STEPHANY JEANETH MACIAS ZELAYA', 'CELESTE EMPERATRIZ MARTINEZ MEJIA',
            'ANA BELINDA VALENZUELA DUARTE'
        ],
        'Partido Liberal' => [
            'ROLANDO ENRIQUE BARAHONA PUERTO', 'ALBERTO EMILIO CRUZ ZELAYA', 'GLORIA ARGENTINA BONILLA BONILLA',
            'YAVHE SALVADOR SABILLON CRUZ', 'HERNAN JOSE MORAZAN DEDIEGO', 'MIRIAN SUYAPA GONZALES CASTILLO',
            'JOSE FRANCISCO MORALES MARTINEZ'
        ],
        'LIBRE' => [
            'RONALD EDGARDO PANCHAME URQUIA', 'JAVIER ADOLFO MIRALDA VILLALOBOS', 'JUAN RAMON FLORES BUEZO',
            'MA. JOSEFINA MEZA SARAVIA', 'GERSON NOE SOLER VALLADARES', 'KAREN SOFIA PONCE',
            'MARIA DEL CARMEN MALDONADO VELASQUEZ'
        ],
        'PSH' => [
            'IRIS ALEJANDRA MEJIA MOLINA', 'JOHANDRA SUSSETTE MEJIA BULNES', 'JOSE ROLANDO BANEGAS PADILLA',
            'EMILIO SANCHEZ CANO', 'JOSE ALFREDO RAMOS PALACIOS', 'ENA MARLENIS DOMINGUEZ ESPINALES',
            'WALDINA LIZETH SANTOS MALDONADO'
        ],
        'DC' => [
            'MOISES RECARTE ALVARADO', 'BETTY LIZETH MARTINEZ BANEGAS', 'JENCY ELIZABETH COREA DIAZ',
            'YENSI NAHUN HERNANDEZ ESCOTO', 'ORFILIA AGUILAR', 'RUDY IRAEL HERNANDEZ BANEGAS',
            'EDYS LEVID CASTAÑEDA GARCIA'
        ]
    ],

    // Copán (7 diputados)
    'Copán' => [
        'Partido Nacional' => [
            'ROY DAGOBERTO CRUZ PEREZ', 'ERIK JOSE ALVARADO ALVARADO', 'JUAN CARLOS LAGOS FUENTES',
            'ALBA YANIRA GUERRA MENDEZ', 'DENIA MARISOL ROMERO MONGE', 'OVIDIO LENIN AYALA ORELLANA',
            'DILCIA JANETH MANCIA CANELO'
        ],
        'Partido Liberal' => [
            'FRANCIS OMAR CABRERA MIRANDA', 'VALESKA YAMILETH VALENZUELA CHAVEZ', 'CRISTHIAM JOSUE HERNANDEZ SAAVEDRA',
            'NORMA ARACELY AGUILAR CHACON', 'MARLON GAMALIEL SANTOS BUESO', 'EVELIN DANELIA RIOS DIAZ',
            'ALEX FABRICIO PORTILLO ARITA'
        ],
        'LIBRE' => [
            'ISIS CAROLINA CUELLAR ERAZO', 'EDUARDO JOSE ELVIR FERRUFINO', 'BRENDA CECILIA SANTOS',
            'JORGE ENRIQUE LOPEZ LOPEZ', 'CARLOS ROBERTO ALFARO CRUZ', 'ZOILA MARILU ESPINOZA ALVARADO',
            'CARLOTA MORAN ESPINOZA'
        ],
        'PSH' => [
            'DIDIER JAIR LOPEZ ESPINOZA', 'NANCY JIESSEL DERAS PORTILLO', 'HELEN ESKARLET PINTO ANDRADE',
            'MARLON ALBERTO ESCOBAR SU', 'NELSON LEMUEL PONTAZA FAJARDO', 'FRANKLIN ADONAY RAMOS AGUILAR',
            'EVELYN ESCOBAR GARCIA'
        ],
        'DC' => [
            'MARIA MAGDALENA ORELLANA JIMENEZ', 'JOSE ADOLFO MEJIA', 'DENIS MIGUEL CACERES CACERES',
            'MARIA GRISELDA ARITA', 'KEIDY NOHEMI DOMINGUEZ', 'PEDRO FRANCISCO ESPINOZA MIRANDA',
            'YADIRA LIZETH ESPINOZA MOLINA'
        ]
    ],

    // Cortés (20 diputados)
    'Cortés' => [
        'Partido Liberal' => [
            'CARLOS ALBERTO UMAÑA DAVID', 'GLORIA YASMIN MEZA ERAZO', 'ALEJANDRA VALLECILLO PAVON',
            'MARLON GUILLERMO LARA ORELLANA', 'SANDRA CAROLINA COLEMAN MILIAN', 'ROBERTO PINEDA CHACON',
            'FERNANDO ENRIQUE CASTRO VALLE', 'THIRSA GABRIELA LOPEZ SOLIS', 'WENCESLAO LARA ORELLANA',
            'NORMAN ALBERTO JIMENEZ', 'OSCAR RENE MUÑOZ CRUZ', 'MARIA DEL CARMEN ANDRADE ZEPEDA',
            'GLORIA KAREN CARRANZA AMAYA', 'KARLA CORITZA ANDRADE VELASQUEZ', 'JOSE DANIEL PAZZETTI PAZ',
            'SANDRA DEL SOCORRO DIAZ', 'JOSE RAMON MARTINEZ RODRIGUEZ', 'NOEL DAVID INOCENTE DERAS',
            'LEIBY MELISSA TORRES ZALAVARRIA', 'ARMANDO BARDALES PAZ'
        ],
        'Partido Nacional' => [
            'JOSE JAAR MUDENAT', 'ROBERTO ENRIQUE COSENZA HERNANDEZ', 'DAISY MARIA ANDONIE LOPEZ',
            'ALBERTO CHEDRANI CASTAÑEDA', 'CINTHYA DAYANARA HAWIT FLORES', 'BRENDA MERCEDES FLORES SERRANO',
            'SANTOS ROBERTO PEÑA ENAMORADO', 'JOHANNA GORETTY COSTA ARITA', 'SHAARON ELIZABETH IZAGUIRRE HEDMAN',
            'SANDRA NOHEMY RAMIREZ VILLANUEVA', 'KAROL IVETTE PINEDA HERNANDEZ', 'JESSICA WALDINA ORDOÑEZ BARDALES',
            'JUAN CARLOS SEGURA GALDAMEZ', 'NANCY DEL CARMEN MORAN VASQUEZ', 'JORGE EDWIN OSEGUERA',
            'FERNANDO ALONSO METZGEN MOREL', 'MARVIN JOSUE GOMEZ ZAPATA', 'JOSE LUIS ARGUETA RAMIREZ',
            'SUSY YANETH VIJIL LOPEZ', 'NAHAMAN HUMBERTO GONZALEZ AVILA'
        ],
        'LIBRE' => [
            'LINDA FRANCES DONAIRE PORTILLO', 'SCHERLY MELISSA ARRIAGA GOMEZ', 'DUNIA YADIRA JIMENEZ AGUILAR',
            'RITA MARIA ZUNIGA MEMBREÑO', 'MAURICIO ANTONIO CASTELLANOS QUIROZ', 'IRIS YANETH PINEDA PAZ',
            'HECTOR SAMUEL MADRID SABILLON', 'VICTALINA MONTENEGRO PINEDA', 'LUIS ROLANDO REDONDO GUIFARRO',
            'RAMON ENRIQUE BARRIOS MALDONADO', 'NETZER EDU MEJIA HERNANDEZ', 'HEIDY GISSELL LAINEZ PONCE',
            'GLADIS ESMERALDA DELCID NIETO', 'ALMA ISABEL MURILLO GABARRETE', 'MARCO ANTONIO CASTELLANOS HERRERA',
            'HEBER FELIPE CRUZ LARA', 'NATIVIDAD REYES RODRIGUEZ', 'KENNIA CAROLINA ORDOÑEZ ALFARO',
            'WILMER LEONID EUCEDA MERAZ', 'JOSE RICARDO GAMERO PAZ'
        ],
        'PSH' => [
            'ROLANDO CONTRERAS MENDOZA', 'KEILYN STEPHANY LOPEZ GUZMAN', 'ROGER ROSALES CHAVARRIA',
            'KITZIA SAYONARA FLORES RIVAS', 'JERRY MEL DIAZ MURILLO', 'ROBERTO DE JESUS CONTRERAS ESCOBAR',
            'ELIZABETH CONTRERAS', 'MARIA MAGDALENA LEIVA MEJIA', 'VICTORIA CAROLINA AGUILAR HOUSE',
            'DORIS YAMILETH CASTILLO ESTEVEZ', 'BELKIS NOHEMY RODRIGUEZ BLANCO', 'MOISES DE JESUS CANAHUATI TURCIOS',
            'KAREN VANESSA MARTINEZ BARAHONA', 'RUBEN ORLANDO GARCIA FAJARDO', 'JERONIMO MARTINEZ ROSALES',
            'DEYADIRA ELIZABETH ALGUERA CABRERA', 'ELVIN FERNANDO LARIOS VELASQUEZ', 'JOSE NATIVIDAD VASQUEZ CRUZ',
            'BLANCA MIRIAN CASTRO CRUZ', 'HEBER JOSUE MALDONADO MEJIA'
        ]
    ],

    // El Paraíso (6 diputados)
    'El Paraíso' => [
        'Partido Nacional' => [
            'HIUDY GABRIELA MORALES AGUILAR', 'GUSTAVO ADOLFO GONZALEZ AGUILAR', 'WALTER ANTONIO CHAVEZ HERNANDEZ',
            'JENNIFER LARISSA PALMA AVILA', 'IDANIA SUYAPA DOBLADO BANEGAS', 'JOSE ANTONIO URRUTIA MARADIAGA'
        ],
        'LIBRE' => [
            'JOHN MILTON GARCIA FLORES', 'EVER NAZAEL AGUILAR AGUILAR', 'MARIO RAFAEL ARGEÑAL MEDINA',
            'OLGA RUTH FLORES SALAZAR', 'NANCY ROSANA BARAHONA SALGADO', 'MELVIN ALEXANDER IZAGUIRRE NUÑEZ'
        ],
        'Partido Liberal' => [
            'PEDRO MENDOZA FLORES', 'YESICA LORENA CANO FLORES', 'MARIO EDGARDO SEGURA AROCA',
            'PABLO HUMBERTO CARRASCO ASCENCIO', 'MELVIN MATIAS BETANCO VARGAS', 'EMILIO CABRERA CABRERA'
        ],
        'PSH' => [
            'JACOBO ADOLFO FLORES', 'KARLA PRICILA ORTIZ', 'SANTOS ERNESTO VELASQUEZ MEDINA',
            'JOSE RAMON SALCEDO LANDAVERDE', 'YESENIA DAMARIS CLAROS DUARTE', 'ELBA NUBIA MIGUEL'
        ],
        'DC' => [
            'MARLON ROBERTO PONCE', 'JAVIER AMILCAR MATUTE VELASQUEZ', 'LOURDES KARINA SANCHEZ',
            'BREISY YORLENY CARRANZA VARGAS', 'GENRRY FABRICIO ESPINAL LOPEZ', 'LEYDIS SARAHI PEREZ CARRANZA'
        ]
    ],

    // Francisco Morazán (23 diputados)
    'Francisco Morazán' => [
        'Partido Nacional' => [
            'KILVETT ZABDIEL JOSSUA BERTRAND BARRIENTOS', 'ARNOLD DANIEL BURGOS BORJAS', 'ADOLFO RAQUEL PINEDA',
            'LISSI MARCELA MATUTE CANO', 'JOHANA GUICEL BERMUDEZ LACAYO', 'SARA ELIZABETH ESTRADA ZAVALA',
            'MARIA JOSE SOSA ROSALES', 'OSWALDO JOSE RAMOS AGUILAR', 'FABIOLA LUCILA ROSA VIGIL',
            'SUYAPA SEHAM MORALES VALERIANO', 'ANTONIO CESAR RIVERA CALLEJAS', 'KIMBERLY SARAI GUEVARA MIRALDA',
            'EDWIN JAVIER CRUZ PERDOMO', 'JOSE LUIS ARGEÑAL VALLADARES', 'YASSER ABDALAH HANDAL CARCAMO',
            'KEVYN DAVID SANDOVAL PADILLA', 'MIRIAM ELISABETH TORRES MEJIA', 'WALESKA JACKELINE ZELAYA SANCHEZ',
            'GRACE MARIELA SIERRA CRUZ', 'OSKAR SALOMON FARAJ HENRIQUEZ', 'KATERIN JAZMIN SALGADO QUIROZ',
            'LOURDES JANETH MEDINA', 'ALBERTO ANTONIO AVILEZ FLORES'
        ],
        'Partido Liberal' => [
            'IROSKA LINDALY ELVIR FLORES', 'SARAI PAMELA ESPINAL LOPEZ', 'EDGARDO RASHID MEJIA GIANNINI',
            'JOSE SALOMON NAZAR ORDOÑEZ', 'JHOSY SADDAM TOSCANO RAMIREZ', 'ALIA NIÑO KAFATY',
            'LUZ ERNESTINA MEJIA PORTILLO', 'MILAGROS DE JESUS GONZALEZ ZELAYA', 'RAFAEL ANTONIO CANALES GIRBAL',
            'KARLA LIZETH ROMERO DAVILA', 'BESAYDA SARAHI VASQUEZ RODRIGUEZ', 'SANDRA MARIBEL FLORES ELVIR',
            'MAXIMINO GERMAN LOBO MUNGUIA', 'KATHERINE ALEJANDRA HERNANDEZ PALENCIA', 'YADIRA WALESKA CALIX GUERRERO',
            'BERNARDO BENJAMIN ANARIBA TOBAR', 'LESLY YAQUELIN LOPEZ CORTES', 'LUIS FERNANDO REYES PONCE',
            'MARTHA PATRICIA HERNANDEZ IZAGUIRRE', 'MANUEL ENRIQUE ANDINO CALIX', 'SALVADOR VIDESMUNDO CABRERA REYES',
            'WILFREDO GARCIA GODOY', 'RAUL ALEXIS CHACON MEDINA'
        ],
        'LIBRE' => [
            'GUSTAVO ENRIQUE GONZALEZ MALDONADO', 'KRITZA JERLIN PEREZ GALLEGOS', 'HUGO ROLANDO NOE PINO',
            'LUCY MICHELL GUERRERO PAZ', 'CLARA MARISABEL LOPEZ PEREZ', 'CARLOS EDUARDO REINA GARCIA',
            'DIEGO JAVIER SANCHEZ CUEVA', 'CARMEN HAYDEE LOPEZ FLORES', 'JARI DIXON HERRERA HERNANDEZ',
            'JUAN ALBERTO BARAHONA MEJIA', 'ROCIO WALKIRIA SANTOS REYES', 'MOHSEN YAMIR MELGHEM RAMOS',
            'MARCO ELIUD GIRON PORTILLO', 'MARIO ORLANDO SUAZO LARA', 'SUYAPA ALEJANDRINA ANDINO FLORES',
            'MIRIAM JANETH OSORTO OSORTO', 'ANDRES ALFREDO CASTRO TURCIOS', 'BEVERLY HAZEL ALEGRIA MOLINA',
            'JOSE MANUEL RODRIGUEZ ROSALES', 'GERMAN OMAR ORTIZ CARRASCO', 'REYNA SAMANTA CASILDO ALVAREZ',
            'MARITZA YAMILETH GONZALES JOYA', 'GERMAN RENE VILLALOBO BARAHONA'
        ],
        'DC' => [
            'GODOFREDO FAJARDO RAMIREZ', 'KAREN YOHANA GUANDIQUE ESTRADA', 'FELICITO AVILA ORDOÑEZ',
            'CEIDY CELESTE CASTAÑEDA CARBAJAL', 'DARIO MANUEL SANCHEZ DUQUE', 'ANGELICA MARIA MARTIN RODRIGUEZ',
            'KATHERINE SOFIA GARCIA CASTRO', 'NORA DEL CARMEN SUAREZ BUSTAMANTE', 'ASHTRY MARISOL MOLINA AGUILERA',
            'MADAI GISSELL VILLALOBOS LAINEZ', 'JOEL NEMUEL NUÑEZ ORDOÑEZ', 'ROSELL EDGARDO RAMOS RODRIGUEZ',
            'RONALD ALONZO MATUS IZAGUIRRE', 'ANDREA SOFIA VALDEZ CERRATO', 'EVER ADALI VARGAZ USEDA',
            'MILLY DAYANA FONSECA ESPINAL', 'SAMUEL ERNESTO CARBAJAL GUZMAN', 'HILDA NORBELIS ANDINO BARAHONA',
            'ANDREA MELISSA SANCHEZ ESPINAL', 'FRANKLIN ALONSO AVILA CARRASCO', 'RONY ALBERTO MONCADA MIDENCE',
            'LUIS ALBERTO ZELAYA MONCADA', 'JORGE ADAN LOPEZ GUZMAN'
        ],
        'PSH' => [
            'JOSE CARLENTON DAVILA MONDRAGON', 'CHARA MARGOTH GONZALEZ PERALTA', 'GERMAN EDGARDO LEITZELAR HERNANDEZ',
            'LUIS DANIEL LEON COELLO', 'NELSON JHOVANNY ALVAREZ ALVAREZ', 'OMAR ANDRES GARCIA CALDERON',
            'JOSE MANUEL MATHEU AMAYA', 'JOSUE VLADIMIR PERDOMO BANEGAS', 'JOSUE DAVID CAÑADAS VALLADARES',
            'SAMMAI MONTSERRAT GIRON GONZALEZ', 'ELIZABETH PALMA', 'ADALID IRIAS MARTINEZ',
            'EIBY MARILYN CARRANZA SANCHEZ', 'OLY RIVIANA AMADOR MARTINEZ', 'MARTHA PAULINA RODAS LAINEZ',
            'ERADIA CERNA SANCHEZ', 'KARLA YOJANA ARZU HENRIQUEZ', 'LILIAN MELISSA AGUILAR ZELAYA',
            'LESLIE ALEJANDRA MEDINA TORRES', 'GLORIA AMELIA GALVEZ GALINDO', 'JOSE ROBERTO MOLINA CACERES',
            'SARAMELIA LEIVA OLIVA', 'HECTOR ALCIDES LOPEZ RUIZ'
        ]
    ],

    // Gracias a Dios (1 diputado)
    'Gracias a Dios' => [
        'Partido Liberal' => ['ERIKA CORINA URTECHO ECHEVERRIA'],
        'LIBRE' => ['KENNEDY CALDERON MATEO'],
        'Partido Nacional' => ['ENDER CASTELLON PEREZ'],
        'PSH' => ['KLENK BOLEAN ESTRADA'],
        'DC' => ['JHONN KENEDY SANTOS MANISTER']
    ],

    // Intibucá (3 diputados)
    'Intibucá' => [
        'Partido Nacional' => [
            'VICTOR NAPOLEON AMADOR MORALES', 'NELSON JAVIER MARQUEZ EUCEDA', 'GENOVEVA JACKELINE MARAVILLA JONES'
        ],
        'LIBRE' => [
            'MARIO AMILCAR PORTILLO CONTRERAS', 'WENDY VANESSA NOCHEZ REYES', 'NORMAN ANTONIO MARQUEZ DIAZ'
        ],
        'Partido Liberal' => [
            'RUMY NAHYP BUESO MEZA', 'EDY CRISTOBAL MEZA ESPINO', 'DANIA EDITH PERDOMO FUNES'
        ],
        'PSH' => [
            'MARIBEL DOMINGUEZ DOMINGUEZ', 'ENRIQUES CHICAS', 'ALEX FERNANDO HERNANDEZ SANCHEZ'
        ],
        'DC' => [
            'BAYRON EDUARDO ORELLANA SANTIAGO', 'KARLA PATRICIA MANUELES INESTROZA', 'MA ASCENSION MARTINES'
        ]
    ],

    // Islas de la Bahía (1 diputado)
    'Islas de la Bahía' => [
        'Partido Nacional' => ['STEPHEN GARRETT GARCIA ARCH'],
        'Partido Liberal' => ['RAYMOND SAMUEL CHERINGTON JOHNSON'],
        'LIBRE' => ['RENE ALEXANDER NUÑEZ SAVOFF'],
        'PSH' => ['YESSY MINELI DIAZ MARTINEZ'],
        'DC' => ['OMAR ROBERTO RAUDALES']
    ],

    // La Paz (3 diputados)
    'La Paz' => [
        'Partido Nacional' => [
            'JUAN JOSE ZERON GONZALEZ', 'GABINO ARGUETA GALVEZ', 'GLORIA MARIA SUYAPA ARGUETA HERRERA'
        ],
        'Partido Liberal' => [
            'ALLAN JOEL PADILLA', 'CAMILO ERNESTO ALVARADO MARTINEZ', 'ESAU SALOMON GARCIA ARGUETA'
        ],
        'LIBRE' => [
            'BAYRON EDUARDO BANEGAS MEJIA', 'ENRIQUE BELPRAN MARTINEZ AVILA', 'AYDEE MARICRUZ HERNANDEZ SORTO'
        ],
        'PSH' => [
            'RONY ARIEL GAMEZ CASTILLO', 'RITA SUSELLE SUAZO RUBIO', 'JUAN FERNANDO ULLOA MEDINA'
        ],
        'DC' => [
            'FRANCISCO ROBERTO MARTINEZ MORALES', 'LUCIO BENITEZ', 'DEISY YAMILETH LAZO PINEDA'
        ]
    ],

    // Lempira (5 diputados)
    'Lempira' => [
        'Partido Nacional' => [
            'LENIN DAVID VALERIANO MENJIVAR', 'WILSON ROLANDO PINEDA DIAZ', 'JOSE VIRGILIO GARCIA ALDANA',
            'STEFFANY MISHELL ROSA GUEVARA', 'ABRAHAM ALVARENGA URBINA'
        ],
        'LIBRE' => [
            'SELVIN OCTAVIO MORALES BONILLA', 'DANY LEONEL MURILLO DIAZ', 'RYNA MARISOL VASQUEZ SANCHEZ',
            'JOSUE DAVID ENAMORADO MADRID', 'YESTER OMAR MUÑOZ'
        ],
        'Partido Liberal' => [
            'MARCO TULIO RODRIGUEZ GAVARRETE', 'MARIO ENRIQUE CALIX LARA', 'WENDY YAMILETH ZUNIGA MORENO',
            'JOSE EDMAN MUÑOZ GOMEZ', 'ANDREA DE JESUS DEL CID GONZALEZ'
        ],
        'PSH' => [
            'JESUS HUMBERTO ALVARADO GOMEZ', 'LUCIA SANTOS SOLA', 'JOSE LEON QUINTANILLA',
            'MARIA SANTOS SUATE', 'JESUS QUINTANILLA BEJARANO'
        ],
        'DC' => [
            'ADRIAN JAFET CACERES TOBAR', 'MARIA ESTELA CORTEZ BENITEZ', 'OSCAR YOVANY DE DIOS CHAVEZ',
            'LINDER EVENOR BOBADILLA REYES', 'MARIA EMERITA REYES BENITEZ'
        ]
    ],

    // Ocotepeque (2 diputados)
    'Ocotepeque' => [
        'Partido Nacional' => ['TANIA GABRIELA PINTO PACHECO', 'EDWIN EDUARDO CHINCHILLA'],
        'Partido Liberal' => ['FANI NOEMI SANTOS PORTILLO', 'OSCAR NECTALY ROSA MALDONADO'],
        'LIBRE' => ['OSCAR ORLANDO CACERES RUIZ', 'DIANA MARIA ERAZO ARITA'],
        'PSH' => ['ASLY NICOLLE AVELAR MELGAR', 'ANGEL MARIA JIMENEZ ESCOBAR'],
        'DC' => ['OLGA ESPERANZA CABRERA ARITA', 'BRAYAN JOSUE PORTILLO HERNANDEZ']
    ],

    // Olancho (7 diputados)
    'Olancho' => [
        'Partido Nacional' => [
            'KARLA PATRICIA FIGUEROA CARDOZA', 'OSCAR EDUARDO RIVERA HENRIQUEZ', 'CARLOS EDUARDO CANO MARTINEZ',
            'FRANCISCO ANTONIO LOPEZ CRUZ', 'KARLA MARTINEZ PAGUADA', 'ANGEL ANTONIO VELASQUEZ MAZZONI',
            'KARLA YOLANY BARAHONA ANTUNEZ'
        ],
        'LIBRE' => [
            'RAFAEL LEONARDO SARMIENTO AGUIRIANO', 'ANGEL DAVID SANDOVAL CERRATO', 'MARCOS RAMIRO LOBO ROSALES',
            'ARMINDA URTECHO MIRALDA', 'ENNIDE MARIELA AGUILAR VELASQUEZ', 'JOSE NECTALY JUAREZ',
            'LARYSSA JOELY AGUIRRE ORTIZ'
        ],
        'Partido Liberal' => [
            'SAMUEL ARMANDO DE JESUS GARCIA SALGADO', 'GUSTAVO ADOLFO ROSA BARAHONA', 'SINDY GABRIELA ORTIZ ZELAYA',
            'GERARDO ALFREDO HERNANDEZ MOYA', 'AMANDA CAROLA BANEGAS GALLEGOS', 'DIPSON MOSEL MIRALDA CALIX',
            'RUTH GUILLEN BONILLA'
        ],
        'DC' => [
            'KEYLA MERARY MOLINA MEJIA', 'JOSE JULIO BARAHONA OLIVA', 'JUAN CARLOS GONZALES',
            'CESAR ORFILIO MEZA GOMEZ', 'GENSUYA NICOLLE MARTINEZ MUNGUIA', 'BLANCA ROSA HERNANDEZ PADILLA',
            'DELBIN NOHEL OCHOA OCHOA'
        ],
        'PSH' => [
            'DARLIN LLANERY FLORES ZELAYA', 'VIRGILIO DE JESUS HERNANDEZ', 'GREISY AZUCENA GARCIA MEJIA',
            'KARLA NAYELI BANEGAS GONZALES', 'KEILYN NOHELIA HERNANDEZ RUIZ', 'ESMIN JESUS CASTRO HERNANDEZ',
            'FIDEL ERNESTO CERRATO HERNANDEZ'
        ]
    ],

    // Santa Bárbara (9 diputados)
    'Santa Bárbara' => [
        'LIBRE' => [
            'EDGARDO ANTONIO CASAÑA MEJIA', 'LUZ ANGELICA SMITH MEJIA', 'SERGIO ARTURO CASTELLANOS PERDOMO',
            'GERMAN OSWALDO ALTAMIRANO DIAZ', 'CRISTIAN DE JESUS HERNANDEZ DIAZ', 'EUNICE EUNICE RAMIREZ MEJIA',
            'JUAN ANGEL LANZA SABILLON', 'ANGEL ADELSO REYES AGUILAR', 'AYLIN LIZETH TEJADA HERNANDEZ'
        ],
        'Partido Nacional' => [
            'MARIO ORLANDO REYES MEJIA', 'MARCOS BERTILIO PAZ SABILLON', 'MARIO ALONSO PEREZ LOPEZ',
            'MARIA FERNANDA SANDRES UMANZOR', 'MIRIAN AZUCENA VILLANUEVA SARMIENTO', 'HECTOR DANILO PERDOMO PAZ',
            'CARMEN JUDITH HERNANDEZ LEIVA', 'KELLYN IVETH ENAMORADO CHAVEZ', 'KRISTO JORDI MEJIA FLORES'
        ],
        'Partido Liberal' => [
            'JOSE ROLANDO SABILLON MUÑOZ', 'RAMON ESTUARDO ENAMORADO RODRIGUEZ', 'SANDRA MARIBEL MANCIA FAJARDO',
            'JOSE BENIGNO PINEDA FERNANDEZ', 'NIXON GEOVANY LEIVA RAPALO', 'JORGE ADALI PAREDES DUBON',
            'TEODOLINDA ANDERSON MEJIA', 'PABLO ERICK BARDALES PINEDA', 'EMILSON DARIO BORJAS PINEDA'
        ],
        'PSH' => [
            'MARIA TERESA MEJIA VALLECILLO', 'GLEDIS GARCIA', 'JOSE DAVID MARTINEZ PERDOMO',
            'GLORIA ESPERANZA HERNANDEZ RODRIGUEZ', 'JULIO NOLASCO', 'NARCISA CABALLERO RAMIREZ',
            'MAINOR JAVIER TROCHEZ HERNANDEZ', 'ALMA ESPERANZA GARCIA GARCIA', 'NELSON CASTELLANOS CASTELLANOS'
        ],
        'DC' => [
            'DONAL ARIEL REYES SANTOS', 'LILIAM ELISABETH ORELLANA BRIONES', 'ELMER ENAMORADO MURILLO',
            'BENIGNO CASTELLANOS CASTELLANOS', 'DONALDO PINEDA CASTELLANOS', 'ANGELA ALEJANDRINA CASTELLANOS TROCHEZ',
            'MAYRA LIZETH BARDALES PEÑA', 'ELVIS NAHUN MEJIA MUÑOZ', 'DINA ELIZABETH ROGEL GUARDADO'
        ]
    ],

    // Valle (4 diputados) - 
    'Valle' => [
        'Partido Nacional' => [
            'JOSE TOMAS ZAMBRANO MOLINA', 'LESLY CAROLINA FLORES MENDEZ', 'JOSUE WILDER MALDONADO VELASQUEZ', 'JUAN ESTEBAN SUAZO LEMUS'
        ],
        'Partido Liberal' => [
            'ALEX FABRICIO ZORTO GARCIA', 'JOSE ALFREDO SAAVEDRA PAZ', 'CARLOS ROBERTO CAMPOS MANZANARES', 'ALEYDA ANTONIA ALVAREZ SIERRA'
        ],
        'LIBRE' => [
            'JOSUE FABRICIO CARBAJAL SANDOVAL', 'LEVIS JOEL GUTIERREZ RODRIGUEZ', 'PAMELA MAXIMINA COELLO ALMENDAREZ', 'PATRICIA GISSEL BUSTILLO MENDOZA'
        ],
        'PSH' => [
            'HUGO OMAR HERNANDEZ CALDERON', 'MIRNA ESPERANZA GALEA VELASQUEZ', 'JELSON ADALY OSORIO ZAVALA', 'KEYBI NAYELI TORRES GUTIERREZ'
        ]
    ],

    // Yoro (9 diputados)
    'Yoro' => [
        'Partido Nacional' => [
            'MAXIMA ALEJANDRA BURGOS HERNANDEZ', 'MILTON JESUS PUERTO OSEGUERA', 'MARCO TULIO GAMEZ DIAZ',
            'EDER LEONEL MEJIA LAINEZ', 'LIDIA YOLANDA CASCO MARTINEZ', 'JORGE ALBERTO GAMEZ ROBLES',
            'JOSE OTILIO VASQUEZ', 'MARIA DEL CARMEN DOMINGUEZ MEJIA', 'LESVI GLORINDA RAMOS'
        ],
        'Partido Liberal' => [
            'MARCO AURELIO TINOCO URBINA', 'GERLEN AMANDA BONILLA LOPEZ', 'LEONEL LOPEZ ORELLANA',
            'DANIELA MARQUEZ RIVERA', 'CHRISTIAN GABRIEL QUESADA ARMIJO', 'JOHANNA JULIETH BUESO SANCHEZ',
            'MARLON YOVANNY MEJIA ULLOA', 'MARLEN ARGENTINA AVILA DAVILA', 'DAVID ANTONIO DURON SUAREZ'
        ],
        'LIBRE' => [
            'FELIPE TOMAS PONCE ISAULA', 'JENIFFER ALEXANDRA DIAZ PONCE', 'MELBI CONCEPCION ORTIZ MURILLO',
            'ARAMINTA PEREIRA ORTEGA', 'CARLOS ANDRES DIAZ BONILLA', 'VICTOR MANUEL MATAMOROS VASQUEZ',
            'EBLIN VANESSA SOTO', 'ZARVIA NOHEMI AMAYA TURCIOS', 'EDGAR ANDRES MARTINEZ SEVILLA'
        ],
        'PSH' => [
            'CARLOS DAVID FERRERA ASSAF', 'LIBERATO MADRID CASTRO', 'DAMARY VENTURA FIGUEROA URBINA',
            'OSMAN JEOVANIE CASTRO MEJIA', 'LUZ MARIA MEJIA MEDINA', 'JUAN CARLOS HERNANDEZ CACERES',
            'SINIA GABRIELA RODRIGUEZ MORALES', 'KARLA YESENIA AMAYA CHAVARRIA', 'OSCAR ALFREDO PEÑA AVILA'
        ],
        'DC' => [
            'JAVIER OMAR CASTILLO MOLINA', 'JUAN FRANCISCO SANTOS BONILLA', 'ROSA ESTELA LANDA RODRIGUEZ',
            'ARLENIS DE JESUS GARCIA CARCAMO', 'GUADALUPE MEJIA RUIZ', 'LILIAN HAYDEE CARCAMO',
            'NICOLAS INESTROZA NARVAEZ', 'GERARDO ANIBAL HERNANDEZ MENCIA', 'WUILMER OMAR CASTRO FIGUEROA'
        ]
    ]
];

try {
    echo "Iniciando inserción de datos REALES de diputados Honduras 2025...\n";
    
    // Obtener todos los departamentos
    $departamentos = dbQuery('SELECT id, nombre FROM departamentos ORDER BY nombre')->fetchAll();
    
    foreach ($departamentos as $depto) {
        $deptoNombre = $depto['nombre'];
        $deptoId = $depto['id'];
        
        if (!isset($partidosDiputados[$deptoNombre])) {
            echo "No hay datos para el departamento: $deptoNombre\n";
            continue;
        }
        
        echo "Procesando $deptoNombre...\n";
        
        foreach ($partidosDiputados[$deptoNombre] as $partido => $candidatos) {
            // Crear planilla para este partido en este departamento
            dbQuery(
                'INSERT INTO planillas (tipo, departamento_id, nombre, partido, descripcion, estado) 
                 VALUES (?, ?, ?, ?, ?, ?)',
                [
                    'diputacion',
                    $deptoId,
                    "Planilla de Diputados $partido - $deptoNombre",
                    $partido,
                    "Candidatos a diputados del partido $partido para el departamento de $deptoNombre",
                    'habilitada'
                ]
            );
            
            // Obtener el ID de la planilla recién insertada
            $planillaIdInsertada = dbQuery('SELECT LAST_INSERT_ID() as id')->fetch()['id'];
            
            // Insertar candidatos
            $numeroSecuencia = 1;
            foreach ($candidatos as $candidato) {
                dbQuery(
                    'INSERT INTO candidatos (planilla_id, nombre, cargo, numero_candidato) 
                     VALUES (?, ?, ?, ?)',
                    [
                        $planillaIdInsertada,
                        $candidato,
                        'Diputado',
                        $numeroSecuencia++
                    ]
                );
            }
            
            echo "  - Partido $partido: " . count($candidatos) . " candidatos\n";
        }
    }
    
    echo "\n✓ Inserción de datos REALES completada exitosamente.\n";
    
    // Mostrar resumen
    $totalPlanillas = dbQuery('SELECT COUNT(*) as total FROM planillas WHERE tipo = ?', ['diputacion'])->fetch()['total'];
    $totalCandidatos = dbQuery('SELECT COUNT(*) as total FROM candidatos c 
                               INNER JOIN planillas p ON c.planilla_id = p.id 
                               WHERE p.tipo = ?', ['diputacion'])->fetch()['total'];
    
    echo "\nResumen:\n";
    echo "- Total planillas de diputados: $totalPlanillas\n";
    echo "- Total candidatos a diputados: $totalCandidatos\n";
    
} catch (Exception $e) {
    echo "Error: " . $e->getMessage() . "\n";
    exit(1);
}
?>